yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main'),
    path('groups/', views.groups, name='groups'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name = 'posts',
        blank=True,
        null=True
    )
    ordering = ['-pub_date']

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group


def index(request):
    NUMBER_OF_POSTS = 10
    template = 'posts/index.html'
    posts = Post.objects.order_by('-pub_date')[:NUMBER_OF_POSTS]
    title = 'Последние обновления на сайте'
    context = {
        'posts': posts,
        'title': title,
    }
    return render(request, template, context)


def group_posts(request, slug):
    NUMBER_OF_POSTS = 10
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    # posts = Post.objects.filter(group=group)[:NUMBER_OF_POSTS]
    posts = group.posts.all()[:NUMBER_OF_POSTS]
    title = 'Записи сообщества ' + group.title
    context = {
        'group': group,
        'posts': posts,
        'title': title,
    }
    return render(request, template, context)


def groups(request):
    template = 'posts/groups.html'
    group = Group.objects.order_by()
    title = "Все группы"
    context = {
        'groups': group,
        'title': title,
    }
    return render(request, template, context)

yatube/templates/base.html
<!DOCTYPE html> 
<html lang="ru">          
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">

    <title>
      {% block title %}
        Контент не подвезли
      {% endblock %}
    </title>
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3">
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>  
</div>  

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
      <a class="navbar-brand" href="{% url 'posts:main' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
  </div>
</nav>


    

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

<title>
  {% block title %}
    {{ title }}
  {% endblock %} 
</title>


{% block content %}
  <div class="container py-5">
    <h1>{{ title }}</h1> 
    {% for post in posts %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <li>
            Описание группы: {{ post.group }}
          </li>
        </ul>
        <p>{{ post.text }}</p>    
        {% if not forloop.last %}<hr>{% endif %}
      </article>
    {% endfor %} 
  </div>
{% endblock %} 

yatube/templates/posts/groups.html
{% extends 'base.html' %}


<title>
  {% block title %}
    {{ title }}
  {% endblock %} 
</title>


{% block content %}
  <div class="container py-5">
      <h1>{{ group.title }}</h1> 
      {% for group in groups %}
        <article>
          <a href="{% url 'posts:group_list' group.slug %}">
            <ul>
                <li>
                    Название группы: {{ group.title }}
                </li>
                <li>
                    Описание группы: {{ group.description }}
                </li>
            </ul>
          </a>
        </article>
      {% endfor %} 
  </div>
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}


<title>
  {% block title %}
    {{ title }}
  {% endblock %} 
</title>


{% block content %}
  <title>{{ title }}</title>
  <div class="container py-5"> 
    <h1>{{ title }}</h1>     
      {% for post in posts %}
        </article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% if not forloop.last %}<hr>{% endif %}
        </article>
      {% endfor %}
    </div>
{% endblock %} 